const KW = {
  "ITK":"Individual Execution Plan (Individuaalne Täitmiskava) — your personal action plan outlining activities and goals for reintegration.",
  "IIP":"Individual Implementation Plan — same as ITK, your roadmap for studying, working, and programs.",
  "personal account":"A financial account opened for you in prison. All transactions go through this — cash is not allowed.",
  "release fund":"Saved portion of your personal account given upon release. Max = 3× Estonian minimum wage.",
  "contact person":"Your main support (inspector-contact person or case manager). Ask them first for most questions.",
  "VEK":"Vangla Ettevõtluskeskus (Prison Entrepreneurship Center) — professional/industrial work in prison.",
  "ETEV":"Electronic monitoring — early release with ankle bracelet tracking your location.",
  "TEV":"Conditional early release on probation — serving remaining sentence in freedom under supervision.",
  "open prison":"Lower-security facility. Free movement during day, may work/study outside.",
  "closed cell":"Cell locked 23 hrs/day. Movement only under escort.",
  "open department":"Cell doors open during day, free movement within department.",
  "risk assessment":"Evaluation of how likely you are to re-offend, based on history and circumstances.",
  "reintegration":"Support and activities to ensure you can live law-abiding after release.",
  "social programs":"Structured programs (anger, addiction, violence) — part of your ITK.",
  "probation officer":"Official supervising you after early release, similar to contact person inside.",
  "solitary confinement":"Disciplinary punishment: alone in cell, restricted rights. Max 14 days (3 if under 21).",
  "count":"Daily roll call — officer checks you're in place and everything is in order.",
  "e-shop":"Prison online store for food, hygiene, clothing, electronics via personal account.",
  "phone card":"Card for prison calls. Transfer money from personal account. Personal phones prohibited.",
  "economic work":"Basic jobs (cleaning, food distribution) — usually your first assignment.",
  "chaplain":"Prison minister providing spiritual support regardless of denomination.",
  "family doctor":"Your assigned GP in prison (perearst). Visits at least once a week.",
  "name tag":"ID worn around neck on strap when outside your cell.",
  "cell terminal":"Device next to cell for radio and communicating with guard room.",
  "disciplinary proceedings":"Formal process for rule violations — evidence gathered, punishment determined.",
};

export default KW;
